name: Auto Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Update packages
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Bucket Updates
        uses: Ash258/Scoop-GithubActions@stable-win
        env:
          GITH_EMAIL: trim21.me@gmail.com
          SKIP_UPDATED: "1"
