name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 2
          path: "my_bucket"
      - name: Checkout Scoop
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          repository: ScoopInstaller/Scoop
          path: "scoop_core"
      - name: Init and Test
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\scoop_core\test\bin\init.ps1
          .\my_bucket\bin\test.ps1
