name: Cron

on:
  push:
    paths:
      - ".github/workflows/cron.yaml"
  schedule:
    # run every 4 hours
    - cron: "20 */4 * * *"

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v2
        with:
          path: "my_bucket"
      - name: Checkout Scoop
        uses: actions/checkout@v2
        with:
          repository: ScoopInstaller/Scoop
          path: "scoop_core"
      - name: Init and Test
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '..\scoop_core')"
          ..\scoop_core\bin\checkver.ps1 -Dir .\bucket\ -Update
        working-directory: "my_bucket"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: "my_bucket"
